- name: Ensure writable dirs
  file:
    state: directory
    follow: yes
    recurse: yes
    mode: 0775
    path: "{{ deploy_next_release_path }}/{{ item }}"
  with_items: "{{ deploy_server_writable_dirs }}"

- name: Set acl permissions for app user for writable dirs
  shell:
    find {{ deploy_next_release_path }}/{{ item }}/ -type d -exec setfacl -m u:{{ deploy_app_user }}:rwx,d:u:{{ deploy_app_user }}:rwx,m::rwx {{ '{}' }} \; &&
    find {{ deploy_next_release_path }}/{{ item }}/ -type f -exec setfacl -m u:{{ deploy_app_user }}:rw,d:u:{{ deploy_app_user }}:rw,m::rw {{ '{}' }} \;
  with_items: "{{ deploy_server_writable_dirs }}"
  when: deploy_use_acl

- name: Set acl permissions for app server user for writable dirs
  shell:
    find {{ deploy_next_release_path }}/{{ item }}/ -type d -exec setfacl -m u:{{ deploy_app_server_user }}:rwx,d:u:{{ deploy_app_server_user }}:rwx,m::rwx {{ '{}' }} \; &&
    find {{ deploy_next_release_path }}/{{ item }}/ -type f -exec setfacl -m u:{{ deploy_app_server_user }}:rw,d:u:{{ deploy_app_server_user }}:rw,m::rw {{ '{}' }} \;
  when: deploy_use_acl and deploy_app_user != deploy_app_server_user
  with_items: "{{ deploy_server_writable_dirs }}"

